### ISSUE TITLE
Will the module be supporting PHP8.1?

### ISSUE THREAD

**Issue by martinshawruroc** [zepgram/magento-dotenv#1]
Hi there,

As title, any plans to support PHP8.1?

I'm in the process of upgrading from PHP7.4 to PHP8.1 and we are currently using this module so it's failing on composer's dependency check

**Comment by zepgram** [comment]
Hello,

Yes of course, I'm doing it soon

**Comment by zepgram** [comment]
I just made it, install should work on php8.1

**Comment by martinshawruroc** [comment]
Brilliant, thank you @zepgram !
