### ISSUE TITLE
Different path to the .env files

### ISSUE THREAD

**Issue by artmouse** [zepgram/magento-dotenv#2]
Greetings!
Is it possible to specify a different path to the .env files, for example on app/etc.

**Comment by zepgram** [comment]
Hello,

Nice suggestion, I added an argument to do this with tag v2.0.1

In order to do it you can use the `get()` method and fulfill the 4th argument:

```php
MagentoDotEnv::get(false, MagentoDotEnv::ENV_KEY, MagentoDotEnv::DEBUG_KEY, 'app/etc')
```

Let me know if you need this on previous tag (php<8.0.2)

**Comment by artmouse** [comment]
Thank you for the useful feature!

**Comment by artmouse** [comment]
PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/var/www/html/app/etc/.env" environment file.

Now empty .env file not created automatically...

**Comment by artmouse** [comment]
An additional check is required. Maybe if there is no .env file, don't need to create a new Symfony DotEnv instance?

**Comment by zepgram** [comment]
Yep you right, I removed it but it's not a good approach. I re-added self-creation of .env file in release 2.0.2 according to the path given in $envFilePath argument

**Comment by artmouse** [comment]
In release 2.0.2 version in composer.json not updated...

**Comment by zepgram** [comment]
Wow sorry I forgot that

**Comment by zepgram** [comment]
updated
